title: Kaleb Kinlaw's homepage
description: Github Pages theme change example
github_username: KalebKinlaw
remote_themes: ages-themes/hacker@v0.2.0
plugins: - jekyll-remote-theme # add this line to the plugins list if you already have one
